task: detection

num_classes: 10
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/mayujie/objectdetection/VisDrone2019-DET/VisDrone2019-DET-train/images
    ann_file: /home/mayujie/objectdetection/VisDrone2019-DET/VisDrone2019-DET-train/annotations/instances_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/mayujie/objectdetection/VisDrone2019-DET/VisDrone2019-DET-val/images
    ann_file: /home/mayujie/objectdetection/VisDrone2019-DET/VisDrone2019-DET-val/annotations/instances_val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False
